version: '3.7'

networks:
  inception:
    driver: bridge

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: unless-stopped

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
    env_file: .env
    depends_on:
      - mariadb
    restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/wordpress
      - ./requirements/nginx/conf/ssl/nginx.crt:/etc/ssl/certs/nginx.crt
      - ./requirements/nginx/conf/ssl/nginx.key:/etc/ssl/private/nginx.key
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/sites-available/default
    depends_on:
      - wordpress
      - mariadb
    restart: unless-stopped

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/robin/data/mariadb

  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/robin/data/wordpress
